/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sniff */

#ifndef _Included_sniff
#define _Included_sniff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sniff
 * Method:    Sniff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sniff_Sniff
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
