/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Helloworld */

#ifndef _Included_Helloworld
#define _Included_Helloworld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Helloworld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Helloworld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
