/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class print */

#ifndef _Included_print
#define _Included_print
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     print
 * Method:    prints
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_print_prints
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
