/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_NativeTask */

#ifndef _Included_com_test_NativeTask
#define _Included_com_test_NativeTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_NativeTask
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_test_NativeTask_runCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
